image: ubuntu

before_script:
  - apt-get update
  - apt-get install -qq npm jpegoptim optipng
  - ln -s /usr/bin/nodejs /usr/bin/node
  - npm install uglify-js clean-css-cli clean-css html-minifier -g

minify:
  script:
    - html-minifier --help
    - mkdir output/
    - html-minifier --minify-css true --minify-js true -o output/index.html index.html
    - uglify-js js/*.js && mv js/ output/
    - cleancss css/*.css
    - mv css/ output/
    - mv fonts output/fonts
    - optipng face.png
    - mv face.png output/
  artifacts:
      paths:
          - output/